apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-configmap--no-prune--ignored
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/instance: test-requires-prune
data:
  key_1: "value_1"
  key_2: "value_2"