apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-requires-prune
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "https://github.com/thesuperzapper/test-argocd.git"
    targetRevision: "main"
    path: "requires-prune/manifests"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "requires-prune"